name: Test deploy

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  # preflight-checks:
  #   name: Preflight checks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check if there are config-sync changes on production
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_CI_USERNAME }}
  #         password: ${{ secrets.SSH_CI_PASSWORD }}
  #         script_stop: true
  #         script: dokku run strapi ../node_modules/.bin/config-sync diff
  deploy:
    name: Deploy
    # needs: [preflight-checks]
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://test.pluginpal.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install plugin dependencies
        run: yarn install

      - name: Build the packages
        run: yarn run build

      - name: Build a Docker image of the playground
        run: |
          cd playground
          docker build \
            --build-arg PUBLIC_URL=${{ secrets.TEST_URL }} \
            -t webtools-playground:latest .
          docker save -o webtools-playground-latest.tar webtools-playground:latest

      - name: Transfer the Docker image to the Dokku server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_CI_USERNAME }}
          password: ${{ secrets.SSH_CI_PASSWORD }}
          source: webtools-playground-latest.tar
          target: /var/lib/dokku/data/storage/strapi/docker-images

      - name: Deploy the Dokku app based on the Docker image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_CI_USERNAME }}
          password: ${{ secrets.SSH_CI_PASSWORD }}
          script_stop: true
          script: |
            sudo docker load -i /var/lib/dokku/data/storage/strapi/docker-images/webtools-playground-latest.tar
            STRAPI_LATEST_IMAGE=$(sudo docker images --format "{{.ID}}" webtools-playground:latest)
            sudo docker tag webtools-playground:latest webtools-playground:$STRAPI_LATEST_IMAGE
            dokku git:from-image strapi webtools-playground:$STRAPI_LATEST_IMAGE
            sudo docker system prune --all --force

